version: '3.9'

services:
  mongodb: 
    image: mongo:5.0.1
    container_name: gp_mongodb_container
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
