@HOST = http://localhost:8080


GET {{HOST}}/check-heath
Content-Type: "application/json"

###
POST {{HOST}}/user/sign-up
Content-Type: "application/json"

{
    "email": "ltkem2103@gmail.com",
    "name": "Kem Lee",
    "password": "password"
}

###
GET {{HOST}}/user/get/642450fca3d31f510c0df407
Content-Type: "application/json"

###
GET {{HOST}}/user/list
x-language-code: "en,ch" 
Content-Type: "application/json"