port: 8080
defaultLanguages: "en"

jwt:
  private_key: "hash_salt"
  access_token_expiration: 86400
  refresh_token_expiration: 86400

mongo:
  uri: "mongodb://admin:password@localhost:27017"
  name: "gpd"